{% set name = "pmgr" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/pmgr/archive/R{{ version }}.tar.gz
  sha256: 3606642357b9899646371a7d6773bf6a38a6fe447bca488891f4a62caa25cc6b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pmgrLauncher.sh = pmgr.pmgr:main
    - pmgrUtils.sh = pmgr.pmgrUtils:main

requirements:
  host:
    - python >=3.9
    - setuptools_scm
    - pip
  run:
    - python >=3.9
    - pyqt >=5
    - pyca >=3.2.0
    - pykerberos >=1.1.14
    - mysqlclient =1.3.12|>=2.0.3
    - docopt
    - pcdsutils

test:
  imports:
    - pmgr
    - pmgr.pmgrUtils
  commands:
    - QT_QPA_PLATFORM="offscreen" pmgrLauncher.sh --help
    - QT_QPA_PLATFORM="offscreen" pmgrUtils.sh --help

about:
  home: https://github.com/pcdshub/pmgr
  dev_url: https://github.com/pcdshub/pmgr
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: LCLS Device Configuration Parameter Manager

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
    - mcb64
