{% set name = "pmgr" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/pmgr/archive/R{{ version }}.tar.gz
  sha256: 0f1a9c7950db62741d450db4fbc2c1d9d5ec6c05a3d03523575afa4d335e9986

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pmgrLauncher.sh = pmgr.pmgr:main
    - pmgrUtils.sh = pmgr.pmgrUtils:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyqt >=5
    - pyca =3.1.1
    - epicscorelibs =7.0.4.99.1.2
    - pykerberos >=1.1.14
    - mysqlclient =1.3.12|>=2.0.3
    - docopt
    - pcdsutils

test:
  imports:
    - pmgr

about:
  home: https://github.com/pcdshub/pmgr
  dev_url: https://github.com/pcdshub/pmgr
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: LCLS Device Configuration Parameter Manager

extra:
  recipe-maintainers:
    - klauer
    - mcb64
    - zllentz
    - zrylettc
