{% set name = "pmgr" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/pmgr/archive/R{{ version }}.tar.gz
  sha256: 0eb5a868e1a7dd40b7be4fea03ce2c35f0fad1362c9d50a9e9c60c509fa05f6e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pmgrLauncher.sh = pmgr.pmgr:main
    - pmgrUtils.sh = pmgr.pmgrUtils:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - docopt
    - epicscorelibs
    - mysqlclient =1.3.12|>=2.0.3
    - numpy
    - pcdsutils
    - pyca
    - pykerberos >=1.1.14
    - pyqt >=5

test:
  imports:
    - pmgr

about:
  home: https://github.com/pcdshub/pmgr
  dev_url: https://github.com/pcdshub/pmgr
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: LCLS Device Configuration Parameter Manager

extra:
  recipe-maintainers:
    - klauer
    - mcb64
    - zllentz
    - zrylettc
